sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
  - yarn install
  - npm install -g grunt
script: grunt build && yarn test-local
