sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
  - yarn global add grunt
script: grunt build && yarn test-local
